//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        [Display(Name = "Mã User")]
        
        public int ID { get; set; }
        
        [Display(Name = "Tên User")]
        [Required(ErrorMessage = "Name not emtpy .....")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Length of the name form 5 - 50 character")]
        public string NameUser { get; set; }

        [DisplayName("Vị trí")]
        public string RoleUser { get; set; }

        [DisplayName("Nhập mật khẩu")]
        [StringLength(16, MinimumLength = 6, ErrorMessage = "Length of the password form 6 - 16 character")]
        [Required(ErrorMessage = "Pass not emtpy ....")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }

        [NotMapped]
        
        [DisplayName("Nhập lại mật khẩu")]
        [Compare("PasswordUser", ErrorMessage = "Password not mactched")]
        [DataType(DataType.Password)]
        public string CofirmPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }
    }
}
